/**
 * Nội dung mẫu hiển thị khi chưa có story nào trong Firestore.
 * Dùng ảnh local từ public/kindness/ và video YouTube thực.
 * isStatic: true — không cho phép sửa/xoá.
 */
export const SAMPLE_STORIES = [
  {
    id: 'lk-1',
    title: 'Ngày Nhà giáo Việt Nam 20/11',
    content: 'Lễ kỷ niệm Ngày Nhà giáo Việt Nam — các em học sinh bày tỏ lòng biết ơn sâu sắc đến thầy cô qua những tiết mục văn nghệ và những bó hoa tươi thắm.',
    imageUrl: '/kindness/le-khiet-20-11.jpg',
    videoUrl: null,
    sourceUrl: null,
    category: 'kindness',
    isFeatured: true,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'lk-2',
    title: 'Tri ân thầy cô — Kỷ niệm 20/11',
    content: 'Khoảnh khắc xúc động trong lễ kỷ niệm Ngày Nhà giáo — nụ cười rạng rỡ của thầy cô khi nhận được tình cảm chân thành từ các em học sinh.',
    imageUrl: '/kindness/le-khiet-20-11-2.jpg',
    videoUrl: null,
    sourceUrl: null,
    category: 'kindness',
    isFeatured: false,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'lk-3',
    title: 'Tiếp sức mùa thi 2024',
    content: 'Chương trình "Tiếp sức mùa thi" — các bạn học sinh tình nguyện hỗ trợ nước uống, quạt mát, thông tin địa điểm thi cho thí sinh và phụ huynh trong những ngày thi căng thẳng.',
    imageUrl: '/kindness/tiep-suc-mua-thi.jpg',
    videoUrl: null,
    sourceUrl: null,
    category: 'community',
    isFeatured: true,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'lk-4',
    title: 'Tình nguyện mùa thi — Lan tỏa yêu thương',
    content: 'Những tình nguyện viên nhỏ tuổi với nụ cười nhiệt huyết — dù nắng gắt, các em vẫn kiên trì hỗ trợ thí sinh suốt những ngày thi quan trọng nhất năm.',
    imageUrl: '/kindness/tiep-suc-mua-thi-2.jpg',
    videoUrl: null,
    sourceUrl: null,
    category: 'community',
    isFeatured: false,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'lk-5',
    title: 'Lễ Tri Ân và Trưởng Thành',
    content: 'Lễ tri ân và trưởng thành — cột mốc đánh dấu hành trình 12 năm đèn sách. Các em học sinh lớp 12 gửi lời cảm ơn đến thầy cô, cha mẹ trước khi bước vào trang mới của cuộc đời.',
    imageUrl: '/kindness/tri-an-truong-thanh.jpg',
    videoUrl: null,
    sourceUrl: null,
    category: 'school',
    isFeatured: true,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'lk-6',
    title: 'Trung Thu Yêu Thương',
    content: 'Đêm hội Trung Thu tràn ngập ánh đèn lồng và tiếng cười — các em học sinh cùng nhau văn nghệ, rước đèn, phá cỗ chia sẻ niềm vui mùa trăng với các bạn có hoàn cảnh khó khăn.',
    imageUrl: '/kindness/trung-thu-yeu-thuong-lk.jpg',
    videoUrl: null,
    sourceUrl: null,
    category: 'kindness',
    isFeatured: true,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'lk-7',
    title: 'Tuyên truyền Bảo vệ Môi trường',
    content: 'Học sinh tích cực tuyên truyền bảo vệ môi trường trong trường và khu dân cư — dùng tranh ảnh, poster sáng tạo để lan tỏa thông điệp xanh đến cộng đồng.',
    imageUrl: '/kindness/le-khiet-tuyen-truyen-bvmt.jpg',
    videoUrl: null,
    sourceUrl: null,
    category: 'environment',
    isFeatured: false,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'lk-8',
    title: 'Vệ sinh trường lớp cuối tuần',
    content: 'Sáng thứ Bảy, các em học sinh tình nguyện ở lại dọn dẹp, lau chùi trường lớp — hành động nhỏ mà ý nghĩa lớn, thể hiện tinh thần trách nhiệm và tình yêu mái trường.',
    imageUrl: '/kindness/ve-sinh-truong-lop-cuoi-tuan.jpg',
    videoUrl: null,
    sourceUrl: null,
    category: 'school',
    isFeatured: false,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'sample-1',
    title: 'Tặng hoa tri ân thầy cô ngày 20/10',
    content: 'Các em tự tay làm thiệp và cắm hoa tặng thầy cô nhân ngày Phụ nữ Việt Nam 20/10. Những bông hoa nhỏ, tấm lòng lớn!',
    imageUrl: '/kindness/co-giao-20-10.jpg',
    videoUrl: null,
    sourceUrl: null,
    category: 'kindness',
    isFeatured: true,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'sample-2',
    title: 'Trung Thu cho em vùng cao',
    content: 'Chương trình "Ánh trăng yêu thương" — các em học sinh gói bánh, mang quà lên tặng các bạn nhỏ vùng cao trong đêm Trung Thu.',
    imageUrl: '/kindness/trung-thu-vung-cao.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=s7Dwa1HqV-s',
    sourceUrl: null,
    category: 'community',
    isFeatured: true,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'sample-3',
    title: 'Học sinh trồng cây xanh trường học',
    content: 'Phong trào trồng cây xanh trong khuôn viên trường — mỗi em trồng một cây, cùng nhau tạo nên không gian học đường xanh - sạch - đẹp.',
    imageUrl: '/kindness/hs-trong-cay.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=nF-xCp-PaUw',
    sourceUrl: null,
    category: 'environment',
    isFeatured: true,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'sample-4',
    title: 'Dự án Bảo vệ Môi trường',
    content: 'Học sinh thu gom rác, tuyên truyền bảo vệ môi trường trong và ngoài trường học. Nhỏ tuổi, lớn tâm!',
    imageUrl: '/kindness/bvmt.jpg',
    videoUrl: null,
    sourceUrl: null,
    category: 'environment',
    isFeatured: false,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'sample-5',
    title: 'Dự án Trang Vàng Kết Nối',
    content: 'Kết nối yêu thương — các em học sinh viết thư, vẽ tranh gửi tặng người già neo đơn và trẻ em có hoàn cảnh khó khăn.',
    imageUrl: '/kindness/trang-vang-1.jpg',
    videoUrl: null,
    sourceUrl: null,
    category: 'community',
    isFeatured: false,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'sample-6',
    title: 'Gây quỹ Noel giúp bạn khó khăn',
    content: 'Chương trình "Giáng Sinh Ấm Áp" — các em bán đồ thủ công tự làm để gây quỹ mua quà tặng các bạn có hoàn cảnh khó khăn.',
    imageUrl: '/kindness/gay-quy-noel.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=o4I1Zr0jc9M',
    sourceUrl: null,
    category: 'kindness',
    isFeatured: false,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'sample-7',
    title: 'Nuôi heo đất gây quỹ Trung Thu',
    content: 'Mỗi ngày bỏ ống một ít, đến Trung Thu đập heo lấy tiền mua quà tặng các bạn nhỏ vùng sâu vùng xa.',
    imageUrl: '/kindness/nuoi-heo-trung-thu.jpg',
    videoUrl: null,
    sourceUrl: null,
    category: 'kindness',
    isFeatured: false,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'sample-8',
    title: 'Tặng quà học sinh khó khăn ngày 30/4',
    content: 'Nhân dịp 30/4, các em cùng thầy cô đến thăm và trao quà cho các bạn học sinh có hoàn cảnh đặc biệt khó khăn.',
    imageUrl: '/kindness/tang-qua-30-4.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=s8wx-J01FGk',
    sourceUrl: null,
    category: 'community',
    isFeatured: false,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'sample-9',
    title: 'Nhật ký việc tử tế',
    content: 'Mỗi ngày ghi lại một việc tốt mình đã làm — từ nhường chỗ ngồi đến dọn rác, nhặt đồ trả người mất. Cùng xây dựng thói quen tử tế!',
    imageUrl: '/kindness/nhat-ki-viec-tu-te.jpg',
    videoUrl: null,
    sourceUrl: null,
    category: 'school',
    isFeatured: false,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
  {
    id: 'sample-10',
    title: 'Tặng nhà tắm cho vùng cao',
    content: 'Dự án xây dựng nhà tắm và công trình vệ sinh cho các trường học vùng núi khó khăn — hành động thiết thực nhất của tình yêu thương.',
    imageUrl: '/kindness/nha-tam-vung-cao.jpg',
    videoUrl: null,
    sourceUrl: null,
    category: 'community',
    isFeatured: false,
    publishedBy: 'system',
    publisherName: 'Ban Giáo vụ',
    publisherPhotoURL: null,
    createdAt: null,
    isStatic: true,
  },
]
